# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:
  
  # cache IDF tools folder
  - task: Cache@2
    displayName: Cache ESP32 tools
    inputs:
      key: 'esp32_tools | 5_1_1'
      restoreKeys: 5_1_1
      path: $(UserProfile)\.espressif\tools
      cacheHitVar: ESP32_TOOLS_CACHE_RESTORED

  # cache pip packages
  - task: Cache@2
    displayName: Cache pip packages
    inputs:
      key: 'python | "$(Agent.OS)" | $(Agent.BuildDirectory)\s\esp-idf\tools\requirements.json'
      restoreKeys: python | "$(Agent.OS)" | $(Agent.BuildDirectory)\s\esp-idf\tools\requirements.json
      path: $(PIP_CACHE_DIR)
      cacheHitVar: PIP_PACKAGES_RESTORED

  # Use Python Version 3.11 and add it to path
  - task: UsePythonVersion@0
    displayName: Set Python to v3.11
    inputs:
      versionSpec: '3.11'
      addToPath: true
          
  # run IDF installers
  - task: PowerShell@2
    displayName: Install IDF (step 1)
    inputs:
      targetType: 'filePath'
      filePath: $(Agent.BuildDirectory)\s\esp-idf\install.ps1
      workingDirectory: $(Agent.BuildDirectory)\s\esp-idf

  - task: PowerShell@2
    displayName: Install IDF (step 2)
    inputs:
      targetType: 'inline'
      workingDirectory: $(Agent.BuildDirectory)\s\esp-idf\tools\requirements
      script: |
        python -m pip install -r requirements.json

  - task: PowerShell@2
    displayName: Install IDF (step 3)
    inputs:
      targetType: 'filePath'
      filePath: $(Agent.BuildDirectory)\s\esp-idf\export.ps1
      workingDirectory: $(Agent.BuildDirectory)\s\esp-idf

  - script: echo "##vso[task.prependpath]C:\Windows\System32"
    displayName: Tweak PATH to reach cmd
